#!/usr/bin/env bash
# a while loop that displays some things based on requirements

a=1
while [ $a -le 10 ]
do
if [ $a -eq 4 ]
then
	echo "bad luck"; 
	((a++));
elif [ $a -eq 8 ]
then
	echo "good luck";
	((a++)); 
else
	echo "Best School";
	((a++));
fi
done
