#!/usr/bin/env bash
# script prints numbers with their superstitious statement

a=1
while [ $a -le 20 ]
do
echo "$a";
case $a in
4)
	echo "bad luck from China"
	((a++))
	;;
9)
	echo "bad luck from Japan"
	((a++))
	;;
17)
	echo "bad luck from Italy"
	((a++))
	;;
*)
	((a++))
	;;
esac
done
